//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etisalat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int employeeID { get; set; }
        public string employeeName { get; set; }
        public string employeeAddress { get; set; }
        public Nullable<int> employeePhone { get; set; }
        public Nullable<int> postion_fk { get; set; }
    
        public virtual Postion Postion { get; set; }
    }
}
