//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etisalat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postion
    {
        public Postion()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int postionID { get; set; }
        public string postionName { get; set; }
        public Nullable<int> department_fk { get; set; }
        public Nullable<int> salary { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
